syntax = "proto3";

package todo;

service TodoService {
  rpc CreateTodo (CreateTodoRequest) returns (TodoResponse);
  rpc GetTodos (GetTodosRequest) returns (GetTodosResponse);
  rpc GetTodoById (GetTodoByIdRequest) returns (TodoResponse);
}

message TodoItem {
  string id = 1;
  string title = 2;
  string description = 3;
  bool completed = 4;
  string user_id = 5;
}

message CreateTodoRequest {
  string title = 1;
  string description = 2;
  string user_id = 3;
}

message TodoResponse {
  TodoItem todo = 1;
}

message GetTodosRequest {
  string user_id = 1;
}

message GetTodosResponse {
  repeated TodoItem todos = 1;
}

message GetTodoByIdRequest {
  string id = 1;
}
